services:
  frontend:
    image: ghcr.io/malshare/frontend
    expose:
      - "80"
    env_file:
      - frontend.env

  cloudflared:
    image: cloudflare/cloudflared:latest
    entrypoint:
      - /bin/sh
      - -c
    command: 'cloudflared tunnel --no-autoupdate run --token "$CLOUDFLARE_TUNNEL_TOKEN"'
    depends_on:
      - frontend
    env_file:
      - frontend.env
